import numpy as np
import matplotlib.pyplot as plt

# for i in range(20):
#     fstem = "pyresults/mg_5.0"
#     spks = np.loadtxt("{}_cellv_{}.dat".format(fstem,i),skiprows=1)
#     plt.figure()
#     plt.plot(spks[:,0],spks[:,1])
#     plt.xlabel("Time (ms)")
#     plt.ylabel("Membrane Potential (mV)")
#     # plt.xlim([-50, 1600])
#     plt.ylim([-70, 10])
#     plt.title("Pyramidal Cell {}".format(i))
#     plt.show()

for mgconc in [0.0, 0.1, 0.5, 1.0, 1.5, 2.0, 5.0]:
    fstem = "pyresults/mg_{}".format(mgconc)
    spks1 = np.loadtxt("{}_cellv_1.dat".format(fstem),skiprows=1)
    spks2 = np.loadtxt("{}_cellv_2.dat".format(fstem),skiprows=1)
    spks3 = np.loadtxt("{}_cellv_7.dat".format(fstem),skiprows=1)
    spks4 = np.loadtxt("{}_cellv_11.dat".format(fstem),skiprows=1)
    plt.figure(figsize=(12,10))
    plt.subplot(4,1,1)
    plt.plot(spks1[:,0],spks1[:,1],'r',label='Cell 1')
    plt.ylabel("Membrane Potential (mV)")
    plt.title("Pyramidal Cell at Mg = {} mM".format(mgconc))
    plt.legend(loc='upper right')
    plt.subplot(4,1,2)
    plt.plot(spks2[:,0],spks2[:,1],'g',label='Cell 2')
    plt.ylabel("Membrane Potential (mV)")
    plt.legend(loc='upper right')
    plt.subplot(4,1,3)
    plt.plot(spks3[:,0],spks3[:,1],'b',label='Cell 7')
    plt.ylabel("Membrane Potential (mV)")
    plt.legend(loc='upper right')
    plt.subplot(4,1,4)
    plt.plot(spks4[:,0],spks4[:,1],'k',label='Cell 11')
    plt.xlabel("Time (ms)")
    plt.ylabel("Membrane Potential (mV)")
    plt.legend(loc='upper right')
    plt.show()